import { styled } from '@mui/system';
import { Button } from '@mui/material';
import {getImageUrl} from '~/swap/util/image-url';

export const ButtonBox = styled(Button)(({ theme }) => ({
  color: '#000000',
  fontSize: '1.5rem',
  fontFamily: 'Roboto-Medium',
  wordWrap: 'break-word',
  borderRadius: '0.9rem',
  border: 'none',
  boxSizing: 'border-box',
  padding: '1.6rem 1.4rem',
  background: 'linear-gradient(352deg, #91C0F8 0%, #AED6F4 58%, #C4E7F2 86%, #C8E9F2 100%)',
  minWidth: 'initial',
  textTransform: 'capitalize',
  overflow: 'hidden',
  // width: 'auto',
  '&.Mui-disabled': {
    cursor: 'not-allowed',
    pointerEvents: 'visible',
    opacity: 0.5,
  },
  '&.border': {
    borderRadius: '12px',
    border: '0.6px solid rgba(255,255,255,.2)',
    background: '#1C1C1C',
    color: `#ffffff`,
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
    position: 'relative',
    zIndex: 2,
    '& img': {
      width: '1.87rem',
      height: '1.87rem',
      marginRight: '1rem',
      '&.iconSuccess': {
        marginRight: '0',
        width: '11px',
        height: '7px',
      },
      '&.x': {
        width: '1.3rem',
        height: '1.2rem',
      },
    },
  },
  '&.userSet': {
    background: 'none',
    backgroundImage: `url(${getImageUrl('user/setbuttonbg.png')})`,
    backgroundSize: '100% 100%',
    backgroundRepeat: 'no-repeat',
    borderRadius: 0,
    border: 'none',
    color: '#EAEAEA',
    fontSize: '1.2rem',
    fontFamily: 'Helvetica Neue',
    fontWeight: 400,
    lineHeight: '1.2rem',
    wordWrap: 'break-word',
    padding: 0,
    '&.order-button': {
      backgroundImage: `url(${getImageUrl('user/order-button.png')})`,
    },
  },
  '&.rightImgBorder': {
    // borderRadius: '1.2rem',
    border: '0.4px solid rgba(255,255,255,.2)',
    background: 'transparent',
    color: `#ffffff`,
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
    fontSize: '1.3rem',
    position: 'relative',
    zIndex: 2,
    '&:before': {
      content: `' '`,
      position: 'absolute',
      left: 0,
      top: 0,
      width: '100%',
      height: '100%',
      // borderRadius: '12px',
      borderRadius: '9px',
      opacity: 0.2,
      border: '0.4px solid rgba(255,255,255,.2)',
      background:
        'linear-gradient(180deg, rgba(245, 244, 239, 0.02) 0%, rgba(108, 108, 96, 0.01) 100%)',
      zIndex: 0,
    },
    '& img': {
      width: '1.2rem',
      height: '1.2rem',
      '&.iconSuccess': {
        marginRight: '0',
        width: '11px',
        height: '7px',
      },
      '&.x': {
        width: '1.3rem',
        height: '1.2rem',
      },
    },
  },
  '&.notBorder': {
    // borderRadius: '1.2rem',
    border: 'none',
    background: '#444547', // 'linear-gradient(0deg, #F5F4F0 0%, #F5F4F0 100%), linear-gradient(93deg, #5856D6 -22.27%, #5AF0FA 33.07%, #B5F079 66.75%, #F1C40F 98.33%, #FD7E14 128.96%)',
    color: `#ffffff`,
    fontFamily: 'Roboto-Medium',
    fontStyle: 'normal',
    fontWeight: 500,
    position: 'relative',
  },
  '&.backBorder': {
    padding: '0.06rem',
    backgroundImage: `linear-gradient(#242424,#242424),linear-gradient(to right,#9CE2D8,#0664C0)`,
    backgroundClip: 'content-box,padding-box',
    transition: 'all 1s',
    color: '#F5F4F0',
    border: '0.06rem solid transparent',
    '&.active': {
      border: '0.06rem solid rgba(255,255,255,.2)',
      background: '#242424',
    },
  },
  '&.fullNotBg': {
    padding: '0.1rem',
    backgroundImage: `linear-gradient(#121212,#121212),linear-gradient(to right,#121212,#121212)`,
    backgroundClip: 'content-box,padding-box',
    transition: 'all 1s',
    color: '#F5F4F0',
    border: '0.6px solid transparent',
    '&.active, &:hover': {
      backgroundImage: `linear-gradient(#121212,#121212),linear-gradient(to right,#9CE2D8,#0664C0)`,
    },
  },
  '&.borderBackBorder': {
    border: '1px solid #6A6A69',
    borderRadius: '0.8rem',
    background: 'linear-gradient(to bottom, #3B3B3B, #272728)',
    transition: 'all 1s',
    color: '#F5F4F0',
    padding: '0.9rem 1.1rem',
  },
  '&.taskBackBorder': {
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
    border: 'none',
    padding: '1px',
    backgroundImage: `linear-gradient(#2F2F2C,#2F2F2C),linear-gradient(93deg, #5856D6 -22.27%, #5AF0FA 33.07%, #B5F079 66.75%, #F1C40F 98.33%, #FD7E14 128.96%)`,
    backgroundClip: 'content-box,padding-box',
    transition: 'all 1s',
  },
  '&.loading': {
    pointerEvents: 'none',
    '&:active': {
      transform: 'none',
    },
    '& .MuiButton-startIcon, & .MuiButton-endIcon': {
      opacity: 0,
      transform: 'scale(0.8)',
    },
  },

  '&:active': {
    '& .content': {
      transform: 'scale(.9)',
    },
  },
  '& .content': {
    zIndex: 1,
    height: '100%',
    width: '100%',
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
    transition: 'opacity 0.2s, transform 0.2s',
  },
  '&.swapButton': {
    height: '2.2rem',
    width: '100%',
    background: 'linear-gradient(352deg, #91C0F8 0%, #AED6F4 58%, #C4E7F2 86%, #C8E9F2 100%)',
    borderRadius: 24,
    color: '#1A202C',
    fontSize: '0.9rem',
    fontFamily: 'Helvetica',
    fontWeight: 700,
    wordWrap: 'break-word',
    '&.chatSend': {
      width: '3rem',
      height: '2.97rem',
      borderRadius: '1rem',
      padding: 0,
      display: 'flex',
      alignItems: 'center',

      '& img': {
        height: '1.5rem',
      },
    },
    '&.startSend': {
      width: '11.5rem',
      height: '3.6rem',
      borderRadius: '1rem',
      padding: 0,
      display: 'flex',
      alignItems: 'center',
      fontSize: '1.4rem',
      color: '#1A202C',
      fontFamily: 'Helvetica Neue',
      fontWeight: '500',
      lineHeight: 14,
      wordWrap: 'break-word',
      '& img': {
        height: '1.5rem',
        marginLeft: '0.8rem',
      },
    },
    '&.newChat': {
      width: '10.1rem',
      height: '2.68rem',
      borderRadius: '0.9rem',
      fontWeight: '400',
      fontSize: '1.3rem',
      '& .newChatPng': {
        height: '1.28rem',
        marginRight: '0.6rem',
      },
    },

    '&.ChatKindD': {
      width: '8.8rem',
      height: '3.7rem',
      fontSize: '1.3rem',
      borderRadius: '3.3rem',
    },
    '&.swapHeader': {
      height: '2rem',
      fontSize: '0.8rem',
      borderRadius: 12,
      padding:'10px',
      [theme.breakpoints.down('sm')]:{
        height: '3rem',
        fontSize: '1.2rem',
        padding:'1rem'
      }
    },
    '&.br12': {
      borderRadius: 12,
    },
    '&.h48': {
      height: '4.8rem',
      fontSize: '2rem',
    },
    '&.wh12': {
      width: '12.4rem',
    },
    '&.provider': {
      height: '3.6rem',
      width: 'auto',
      color: 'black',
      fontSize: '1.4rem',
      fontFamily: 'Helvetica Neue',
      fontWeight: 500,
      wordWrap: 'break-word',
    },
  },
  '&.card': {
    background: 'linear-gradient(288deg, #91C0F8 13.91%, #D7F4F0 103.71%, #F175BE 153.96%, #E96C00 177.18%)',
    color: '#000000',
    fontFamily: 'Helvetica',
    wordWrap: 'break-word',
    fontWeight: 500,
  },
  [theme.breakpoints.down('sm')]: {
    '&.swapButton': {
      '&.startSend': {
        width: '9rem',
        height: '3rem',
        borderRadius: '0.8rem',
        fontSize: '1.2rem',
        lineHeight: 12,
        '& img': {
          height: '1.2rem',
          marginLeft: '0.6rem',
        },
      },
    },
  },
}));
